apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.opserverExternalSecret.name }}
spec:
  refreshInterval: {{ .Values.opserverExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.opserverExternalSecret.storeRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.opserverExternalSecret.targetName }}
  data:
  - secretKey: oktaClientId
    remoteRef:
      key: {{ .Values.opserverExternalSecret.remoteRefs.oktaClientId }}
  - secretKey: oktaClientSecret
    remoteRef:
      key: {{ .Values.opserverExternalSecret.remoteRefs.oktaClientSecret }}
